# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Juehc5xO-_Tb5N3PGgTIe2hOGp85S568
"""

import math_operation
math_operation.add(12,13)

import math_operation
math_operation.subtract(12,8)

import math_operation
math_operation.multiply(12,13)

math_operation
math_operation.divide(15,3)